// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwfikpmizvfkihybmnws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3ZmlrcG1penZma2loeWJtbndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTc3NTYsImV4cCI6MjA3MDczMzc1Nn0.8J3nsoZRJgtnjVCwsTZ_phK31ZABGGnUCV4uZCMYDOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});